import test from "node:test";import assert from "node:assert/strict";
const calc=await import(new URL("../app/calculations.ts",import.meta.url));
test("general one room",()=>{const r=calc.areaResult([{length:10,width:12}],10);assert.deepEqual([r.measured,r.allowanceArea,r.finalArea],[120,12,132])});
test("general multiple and boxes",()=>{const r=calc.areaResult([{length:10,width:12},{length:8,width:10}],10,23.5);assert.deepEqual([r.measured,r.allowanceArea,r.finalArea,r.packages],[200,20,220,10])});
test("tile",()=>{const r=calc.pieceResult([{length:10,width:10}],1,1,10,12);assert.deepEqual([r.before,r.total,r.packages],[100,110,10])});
test("vinyl",()=>{const r=calc.pieceResult([{length:12,width:15}],4,.5,10,10);assert.deepEqual([r.before,r.total,r.packages],[90,99,10])});
test("laminate",()=>{const r=calc.areaResult([{length:14,width:11}],10,21.5);assert.deepEqual([r.finalArea,r.packages],[169.4,8])});
test("hardwood",()=>{const r=calc.areaResult([{length:15,width:16}],10,20);assert.deepEqual([r.finalArea,r.packages],[264,14])});
test("metric",()=>{const r=calc.areaResult([{length:4,width:5}],10,2.2);assert.deepEqual([r.measured,r.allowanceArea,r.finalArea,r.packages],[20,2,22,10])});
test("rounding",()=>assert.equal(calc.areaResult([{length:100.01,width:1}],0,20).packages,6));
test("validation",()=>{for(const fn of [()=>calc.areaResult([{length:0,width:1}],10),()=>calc.areaResult([{length:-1,width:1}],10),()=>calc.areaResult([{length:1,width:1}],-1),()=>calc.areaResult([{length:1,width:1}],10,0)])assert.throws(fn)});
test("carpet narrower than roll",()=>{const r=calc.carpetResult([{length:10,width:11}],12,10);assert.equal(r.length,11);assert.equal(r.materialArea,132)});
test("carpet wider, custom roll",()=>{const r=calc.carpetResult([{length:10,width:13}],12,0);assert.equal(r.length,20)});
test("carpet multiple metric",()=>{const r=calc.carpetResult([{length:4,width:3},{length:5,width:4}],4,10);assert.equal(r.length,9.9);assert.equal(r.allowanceArea,3.2)});
