import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";
const files=await Promise.all(["app/layout.tsx","app/[[...slug]]/page.tsx","app/sitemap.ts","app/robots.ts","app/guides/[slug]/page.tsx"].map(async p=>[p,await readFile(p,"utf8")]));const source=files.map(x=>x[1]).join("\n");
test("old brand and old domain are absent",()=>{assert.doesNotMatch(source,/Floorwise|floorwise-calculators\.sites\.openai/i)});
test("production domain is centralized",async()=>{const config=await readFile("app/site-config.ts","utf8");assert.match(config,/https:\/\/floorscalc\.com/);assert.match(config,/FloorsCalc/)});
test("all internal literal links point to known pages",()=>{const links=[...source.matchAll(/href="(\/[^"]*)"/g)].map(x=>x[1]);const known=new Set(["/","/calculators","/guides","/about","/contact","/privacy","/terms","/general-flooring-calculator"]);for(const link of links)assert.ok(known.has(link),`Unknown internal link: ${link}`)});
test("SEO endpoints and custom 404 exist",async()=>{for(const path of ["app/sitemap.ts","app/robots.ts","app/not-found.tsx"])assert.ok((await readFile(path,"utf8")).length>20)});
test("contact route protects secrets and spam",async()=>{const route=await readFile("app/api/contact/route.ts","utf8");assert.match(route,/RESEND_API_KEY/);assert.match(route,/CONTACT_EMAIL/);assert.match(route,/CONTACT_FROM_EMAIL/);assert.match(route,/website/);assert.match(route,/LIMIT=5/)});
test("every calculator has imperial and metric worked examples",async()=>{const calculator=await readFile("app/Calculator.tsx","utf8");for(const kind of ["general","tile","vinyl","laminate","hardwood","carpet"]){const start=calculator.indexOf(` ${kind}:{`);assert.ok(start>=0,`Missing ${kind} copy`);const next=calculator.indexOf("\n+",start);const block=calculator.slice(start,next<0?calculator.length:next);assert.match(block,/imperial:\{method:/);assert.match(block,/metric:\{method:/);assert.match(block,/example:/)}assert.match(calculator,/data-unit=\{unit\}/)});
test("general box coverage is simple and unit-aware",async()=>{const calculator=await readFile("app/Calculator.tsx","utf8");assert.match(calculator,/Coverage per box \(\{areaUnit\}\) — optional/);assert.match(calculator,/Example: 22\.45/);assert.match(calculator,/Example: 2\.09/);assert.match(calculator,/Enter the square-meter coverage printed on one flooring box/);assert.doesNotMatch(calculator,/Package method/)});
