"use client";
import { useState } from "react";
import { areaResult, carpetResult, inchesToFeet, centimetersToMeters, pieceResult, type Room, type Unit } from "./calculations";

type Kind = "general"|"tile"|"vinyl"|"laminate"|"hardwood"|"carpet";
const labels:Record<Kind,string>={general:"General flooring",tile:"Tile",vinyl:"Vinyl plank",laminate:"Laminate",hardwood:"Hardwood",carpet:"Carpet"};
const fmt=(n:number)=>Number(n.toFixed(2)).toLocaleString();
export default function Calculator({kind}:{kind:Kind}) {
 const [unit,setUnit]=useState<Unit>("imperial"), [rooms,setRooms]=useState<Room[]>([{name:"Room 1",length:10,width:12}]);
 const [allowance,setAllowance]=useState(10), [productL,setProductL]=useState(kind==="tile"?12:48), [productW,setProductW]=useState(kind==="tile"?12:6);
 const [packMode,setPackMode]=useState("coverage"), [packValue,setPackValue]=useState(""), [rollWidth,setRollWidth]=useState(12), [errors,setErrors]=useState<string[]>([]);
 const areaUnit=unit==="imperial"?"sq ft":"m²", lengthUnit=unit==="imperial"?"ft":"m";
 function update(i:number,key:keyof Room,value:string){setRooms(rooms.map((r,j)=>j===i?{...r,[key]:key==="name"?value:Number(value)}:r));}
 let result:any=null; const validation:string[]=[];
 try { const coverage=packValue===""?undefined:Number(packValue); if(kind==="carpet") result=carpetResult(rooms,rollWidth,allowance); else if(kind==="general"||kind==="hardwood") result=areaResult(rooms,allowance,coverage); else {const factor=unit==="imperial"?inchesToFeet:centimetersToMeters; result=pieceResult(rooms,factor(productL),factor(productW),allowance,packMode==="pieces"&&coverage?coverage:undefined,packMode==="coverage"?coverage:undefined);} } catch(e){validation.push((e as Error).message)}
 const submit=(e:React.FormEvent)=>{e.preventDefault();setErrors(validation)};
 return <section className="calculator" aria-labelledby="tool-title"><h2 id="tool-title">{labels[kind]} calculator</h2>
  <form onSubmit={submit} noValidate>
   <fieldset className="unit-toggle"><legend>Measurement system</legend><label><input type="radio" checked={unit==="imperial"} onChange={()=>setUnit("imperial")}/> Imperial</label><label><input type="radio" checked={unit==="metric"} onChange={()=>setUnit("metric")}/> Metric</label></fieldset>
   <h3>Rooms or areas</h3>{rooms.map((r,i)=><div className="room" key={i}><label>Room name <input value={r.name||""} onChange={e=>update(i,"name",e.target.value)}/></label><label>Length ({lengthUnit}) <input type="number" min="0.01" max="10000" step="any" value={r.length} onChange={e=>update(i,"length",e.target.value)} required/></label><label>Width ({lengthUnit}) <input type="number" min="0.01" max="10000" step="any" value={r.width} onChange={e=>update(i,"width",e.target.value)} required/></label>{rooms.length>1&&<button type="button" className="text-button" onClick={()=>setRooms(rooms.filter((_,j)=>i!==j))}>Remove room</button>}</div>)}
   <button type="button" className="secondary" onClick={()=>setRooms([...rooms,{name:`Room ${rooms.length+1}`,length:10,width:10}])}>Add another room</button>
   {!["general","carpet"].includes(kind)&&<div className="product"><h3>{kind==="hardwood"?"Fixed board dimensions (optional)":"Product dimensions"}</h3><label>Length ({unit==="imperial"?"in":"cm"}) <input type="number" min="0.01" step="any" value={productL} onChange={e=>setProductL(Number(e.target.value))}/></label><label>Width ({unit==="imperial"?"in":"cm"}) <input type="number" min="0.01" step="any" value={productW} onChange={e=>setProductW(Number(e.target.value))}/></label></div>}
   {kind==="carpet"?<label>Carpet roll width ({lengthUnit}) <input type="number" min="0.01" step="any" value={rollWidth} onChange={e=>setRollWidth(Number(e.target.value))}/></label>:<div><label>Package method <select value={packMode} onChange={e=>setPackMode(e.target.value)}><option value="coverage">Coverage per package</option>{!["general","hardwood"].includes(kind)&&<option value="pieces">Pieces per box</option>}</select></label><label>{packMode==="coverage"?`Coverage per package (${areaUnit})`:"Pieces per box"} (optional) <input type="number" min="0.01" step="any" value={packValue} onChange={e=>setPackValue(e.target.value)}/></label></div>}
   <label>Material allowance (%) <input type="number" min="0" max="50" step="0.1" value={allowance} onChange={e=>setAllowance(Number(e.target.value))}/><small>10% is a recommended starting point, not a hidden assumption.</small></label>
   {errors.map((x,i)=><p className="error" key={i}>{x}</p>)}<div className="actions"><button type="submit">Update results</button><button type="button" className="secondary" onClick={()=>{setRooms([{name:"Room 1",length:10,width:12}]);setAllowance(10);setPackValue("");setErrors([])}}>Reset</button></div>
  </form>
  {result&&<div className="results" aria-live="polite"><h3>Result breakdown</h3><dl>{result.areas.map((a:number,i:number)=><div key={i}><dt>{rooms[i].name||`Area ${i+1}`}</dt><dd>{fmt(a)} {areaUnit}</dd></div>)}<div><dt>Combined measured area</dt><dd>{fmt(result.measured)} {areaUnit}</dd></div>{unit==="imperial"&&<div><dt>Measured area in square yards</dt><dd>{fmt(result.measured/9)} sq yd</dd></div>}<div><dt>Material allowance ({allowance}%)</dt><dd>{fmt(result.allowanceArea)} {areaUnit}</dd></div><div><dt>Final material area</dt><dd>{fmt(result.finalArea)} {areaUnit}</dd></div>{result.pieceArea&&<><div><dt>Individual piece area</dt><dd>{fmt(result.pieceArea)} {areaUnit}</dd></div><div><dt>Pieces before allowance</dt><dd>{fmt(result.before)}</dd></div><div><dt>Allowance piece quantity</dt><dd>{fmt(result.allowancePieces)}</dd></div><div><dt>Whole pieces required</dt><dd>{result.total} (rounded up)</dd></div></>}{result.packages&&<div><dt>Whole packages required</dt><dd>{result.packages} (rounded up)</dd></div>}{kind==="carpet"&&<><div><dt>Selected roll width</dt><dd>{fmt(result.rollWidth)} {lengthUnit}</dd></div><div><dt>Estimated carpet length</dt><dd>{fmt(result.length)} {lengthUnit}</dd></div><div><dt>Estimated roll material</dt><dd>{fmt(result.materialArea)} {areaUnit}</dd></div></>}</dl><button type="button" onClick={()=>window.print()}>Print results</button>{kind==="carpet"&&<p className="notice"><strong>Planning estimate:</strong> actual requirements may change with roll direction, orientation, seams, pattern matching, doorways, closets, hallways, stairs, irregular shapes, and installer layout decisions.</p>}</div>}
 </section>
}
